# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25c28feaaf4cc9cb9dfd6e6ada067e800edbb3cb8dd70d33a84fb2df57aed4f9c8f2ba7bffb146239f4d3a05988d9d6fdd0320aa7ece0dffc01e4fb93e08bdfa

test:
  secret_key_base: fbec9963e526ea5713e7965e9618b0b8b37f8cefda5ebd914457e72d4c937ea2d5a5819ca2a9531dad53229881261216d735f2f7f9d594d52972d73a4be8b685

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
